// <auto-generated />
namespace Tatil_Seyahat_Sitesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202501121120128_add-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
